/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.daoUsuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author viniv
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
        //getContentPane().setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtCpfUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        edtSenhaConfirmacao = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JToggleButton();
        edtNivelAcessoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtDataNascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setText("Nome");

        edtNomeUsuario.setPreferredSize(new java.awt.Dimension(300, 22));
        edtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Cpf");

        edtCpfUsuario.setPreferredSize(new java.awt.Dimension(300, 22));
        edtCpfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha");

        edtSenha.setPreferredSize(new java.awt.Dimension(300, 22));

        edtSenhaConfirmacao.setPreferredSize(new java.awt.Dimension(300, 22));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        edtNivelAcessoUsuario.setPreferredSize(new java.awt.Dimension(300, 22));
        edtNivelAcessoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNivelAcessoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Nivel de Acesso");

        jLabel5.setText("Data de Nascimento");

        edtDataNascimento.setPreferredSize(new java.awt.Dimension(300, 22));
        edtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(edtNivelAcessoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCpfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtSenhaConfirmacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnSalvar)
                        .addGap(59, 59, 59)
                        .addComponent(btnLimpar))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(edtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(edtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(edtNivelAcessoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edtSenhaConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addGap(64, 64, 64))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeUsuarioActionPerformed

    private void edtCpfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfUsuarioActionPerformed

    private void edtNivelAcessoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNivelAcessoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNivelAcessoUsuarioActionPerformed

    private void edtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataNascimentoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        edtCpfUsuario.setText("");
        edtDataNascimento.setText("");
        edtNivelAcessoUsuario.setText("");
        edtNomeUsuario.setText("");
        edtSenhaConfirmacao.setText("");
        edtSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Usuario u = new Usuario();
        u.setCpf(edtCpfUsuario.getText().toString());
        u.setDataNascimento(edtDataNascimento.getText().toString());
        u.setUsuario(edtNomeUsuario.getText().toString());
        u.setStatusDoUsuario(edtNivelAcessoUsuario.getText().toString());
        u.setSenhaDoUsuario(edtSenha.getText().toString());
           
        if (edtSenha.getText().equals(edtSenhaConfirmacao.getText())) {
            u.setSenhaDoUsuario(edtSenha.getText().toString());
            if (validarCampos()) {
                dao.daoUsuario daoU = new daoUsuario();
                if(daoU.salvarUsuario(u)) {
                    TelaLogin tl = new TelaLogin();
                    tl.setVisible(true);
                    dispose();
                    
                }else{
                    
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "confirme a senha do usuario");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private boolean validarCampos(){
        if (edtNomeUsuario.getText().length()>0) {
            if (edtCpfUsuario.getText().length()>0) {
                if (edtDataNascimento.getText().length()>0) {
                    if (edtNivelAcessoUsuario.getText().length()>0){
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Preencha o nivel de acesso do usuario");
                        return false;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Preencha a data de nascimento do usuario");
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha o cpf do usuario");
                return false;
            }
        }else {
            JOptionPane.showMessageDialog(null, "Preencha o nome do usuario");
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<ediedtNomeUsuariofaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JTextField edtCpfUsuario;
    private javax.swing.JTextField edtDataNascimento;
    private javax.swing.JTextField edtNivelAcessoUsuario;
    private javax.swing.JTextField edtNomeUsuario;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JPasswordField edtSenhaConfirmacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
